/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.showapi;

import java.util.ArrayList;
import javax.swing.DefaultListModel;

/**
 *
 * @author ryankent
 */
public class Details extends javax.swing.JFrame {

    private DefaultListModel<String> dlmEpisodes;
    private Object myLock = new Object();
    private ShowDetails currentResponse;
    private int id;
    private Episode temp;
    
    /**
     * Creates new form PopularitySearch
     */
    public Details(int id) {
        
        dlmEpisodes = new DefaultListModel();
        this.id = id;
        initComponents();
        

    }
      
    public void detailsSearch(int id) {
        String url = "https://www.episodate.com/api/show-details?q=" + id;
        try {
            synchronized(myLock){
                currentResponse = ShowDetails.fill(url);
                updateEpisodeResults();
                
                //updateSearchResults();
            }
        } catch (Exception ex) { 
        }
    }
    
    public void threadedSearch(int id) {
        Thread thread = new Thread(new Runnable(){
            public void run() {
                detailsSearch(id);
            }
        }); 
        thread.start();   
    }
    
    
    
    public void updateEpisodeResults() {
        //System.out.println(currentResponse);
        showDescriptionArea.setText(currentResponse.getDescription());
        ArrayList<Episode> showEpisodes = currentResponse.getEpisodes();
        dlmEpisodes.clear();
        for(int i = 0; i < showEpisodes.size(); i++) {
            dlmEpisodes.addElement("Season: " + showEpisodes.get(i).getSeason() + ", Episode: "+ showEpisodes.get(i).getEpisode() + " - " + showEpisodes.get(i).getName());
            
        }  
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        showList = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        showDescriptionArea = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        showList.setModel(dlmEpisodes);
        jScrollPane1.setViewportView(showList);

        showDescriptionArea.setColumns(20);
        showDescriptionArea.setLineWrap(true);
        showDescriptionArea.setRows(5);
        jScrollPane2.setViewportView(showDescriptionArea);

        jLabel1.setText("Description:");

        jLabel2.setText("Episodes: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    


    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea showDescriptionArea;
    private javax.swing.JList<String> showList;
    // End of variables declaration//GEN-END:variables
}
