/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.showapi;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author ryankent
 */
public class UserListWindow extends javax.swing.JFrame {

    private DefaultListModel<ShowResults> userList;
    private DefaultListModel<ShowResults> showResults;
    private ShowResults currentShow;
    private ShowResults tempShow;
    private String rating;
    private int temp;
    
    /**
     * Creates new form UserListWindow
     */
    public UserListWindow(DefaultListModel<ShowResults> userList) {
        
        this.userList = userList;
        
        initComponents();
       
        userInputList.setCellRenderer(new ResultCellRenderer());     
    }
    
    public void updateCurrentShow(){
        currentShowComments.setText(currentShow.getComments());
        currentShowRating.setText(currentShow.getRating());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        userInputList = new javax.swing.JList<>();
        addCommentButton = new javax.swing.JButton();
        addRatingButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        currentShowComments = new javax.swing.JTextArea();
        currentShowRating = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        userInputList.setModel(userList);
        userInputList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                userInputListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(userInputList);

        addCommentButton.setText("Add Comments");
        addCommentButton.setEnabled(false);
        addCommentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCommentButtonActionPerformed(evt);
            }
        });

        addRatingButton.setText("Add Rating");
        addRatingButton.setEnabled(false);
        addRatingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addRatingButtonActionPerformed(evt);
            }
        });

        currentShowComments.setColumns(20);
        currentShowComments.setLineWrap(true);
        currentShowComments.setRows(5);
        jScrollPane2.setViewportView(currentShowComments);

        jLabel1.setText("Rating:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(addCommentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(currentShowRating, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(addRatingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(addRatingButton)
                        .addGap(18, 18, 18)
                        .addComponent(addCommentButton)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(currentShowRating, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addRatingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addRatingButtonActionPerformed
        tempShow = userInputList.getSelectedValue();
        String newRating = JOptionPane.showInputDialog(this,"Add a rating out of 10","Set a show's rating",2);
        //Integer.parseInt(newRating);
        tempShow.setRating(newRating);
        if (newRating != null) {
            updateCurrentShow();
        }
        //userInputList.getSelectedValue(tempShow.setComments(newRating));
    }//GEN-LAST:event_addRatingButtonActionPerformed

    private void addCommentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCommentButtonActionPerformed
        tempShow = userInputList.getSelectedValue();
        String newComment = JOptionPane.showInputDialog(this,"Add show comments","Add comments to a show",2);
        tempShow.setComments(newComment);
        if (newComment != null)
            updateCurrentShow();
    }//GEN-LAST:event_addCommentButtonActionPerformed

    private void userInputListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_userInputListValueChanged
        currentShow = userInputList.getSelectedValue();
        updateCurrentShow();        // TODO add your handling code here:
   
        addRatingButton.setEnabled(true);
        addCommentButton.setEnabled(true);
    }//GEN-LAST:event_userInputListValueChanged

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCommentButton;
    private javax.swing.JButton addRatingButton;
    private javax.swing.JTextArea currentShowComments;
    private javax.swing.JTextField currentShowRating;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<ShowResults> userInputList;
    // End of variables declaration//GEN-END:variables
}
